### ISSUE TITLE
🤖 ACoE - Package move request

### ISSUE THREAD

**Issue by SahanaGowdaBV** [SahanaGowdaBV/github_Job_name_variable#1]
```yaml
process_name: test
process_version: 1.2.3
change_reason: testing
```
