### ISSUE TITLE
🤖 ACoE - Package move request

### ISSUE THREAD

**Issue by SahanaGowdaBV** [SahanaGowdaBV/github_Job_name_variable#2]
```yaml
process_name: test
process_version: 0.1.2
change_reason: testing
```
