### ISSUE TITLE
jq

### ISSUE THREAD

**Issue by SahanaGowdaBV** [SahanaGowdaBV/github_Job_name_variable#24]
```yaml
process_name: <process_name>
process_version: <process_version>
change_reason: <change_reason>
```
