### ISSUE TITLE
🤖 ACoE - Package move request

### ISSUE THREAD

**Issue by SahanaGowdaBV** [SahanaGowdaBV/github_Job_name_variable#4]
```yaml
process_name: 1
process_version: 2
change_reason: 3
```
